// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sever.proto

package command

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CSLogin struct {
	Userid               uint64   `protobuf:"varint,1,opt,name=userid,proto3" json:"userid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CSLogin) Reset()         { *m = CSLogin{} }
func (m *CSLogin) String() string { return proto.CompactTextString(m) }
func (*CSLogin) ProtoMessage()    {}
func (*CSLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1ca773a84dec372, []int{0}
}

func (m *CSLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CSLogin.Unmarshal(m, b)
}
func (m *CSLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CSLogin.Marshal(b, m, deterministic)
}
func (m *CSLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CSLogin.Merge(m, src)
}
func (m *CSLogin) XXX_Size() int {
	return xxx_messageInfo_CSLogin.Size(m)
}
func (m *CSLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_CSLogin.DiscardUnknown(m)
}

var xxx_messageInfo_CSLogin proto.InternalMessageInfo

func (m *CSLogin) GetUserid() uint64 {
	if m != nil {
		return m.Userid
	}
	return 0
}

type SCLogin struct {
	Userid               uint64   `protobuf:"varint,1,opt,name=userid,proto3" json:"userid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SCLogin) Reset()         { *m = SCLogin{} }
func (m *SCLogin) String() string { return proto.CompactTextString(m) }
func (*SCLogin) ProtoMessage()    {}
func (*SCLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1ca773a84dec372, []int{1}
}

func (m *SCLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SCLogin.Unmarshal(m, b)
}
func (m *SCLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SCLogin.Marshal(b, m, deterministic)
}
func (m *SCLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SCLogin.Merge(m, src)
}
func (m *SCLogin) XXX_Size() int {
	return xxx_messageInfo_SCLogin.Size(m)
}
func (m *SCLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_SCLogin.DiscardUnknown(m)
}

var xxx_messageInfo_SCLogin proto.InternalMessageInfo

func (m *SCLogin) GetUserid() uint64 {
	if m != nil {
		return m.Userid
	}
	return 0
}

func init() {
	proto.RegisterType((*CSLogin)(nil), "command.CSLogin")
	proto.RegisterType((*SCLogin)(nil), "command.SCLogin")
}

func init() { proto.RegisterFile("sever.proto", fileDescriptor_e1ca773a84dec372) }

var fileDescriptor_e1ca773a84dec372 = []byte{
	// 87 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x4e, 0x2d, 0x4b,
	0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4f, 0xce, 0xcf, 0xcd, 0x4d, 0xcc, 0x4b,
	0x51, 0x52, 0xe4, 0x62, 0x77, 0x0e, 0xf6, 0xc9, 0x4f, 0xcf, 0xcc, 0x13, 0x12, 0xe3, 0x62, 0x2b,
	0x2d, 0x4e, 0x2d, 0xca, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x09, 0x82, 0xf2, 0x40, 0x4a,
	0x82, 0x9d, 0xf1, 0x2a, 0x49, 0x62, 0x03, 0x9b, 0x6a, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x51,
	0x60, 0x0b, 0x73, 0x64, 0x00, 0x00, 0x00,
}
